### ISSUE TITLE
[BUG]: Error facing in the sample `demo-randomerror-js` |

### ISSUE THREAD

**Issue by arjunumenon** [microsoft/dev-proxy#948]
### Description

When I follow the [instructions which](https://github.com/pnp/proxy-samples/tree/main/samples/demo-randomerror-js#minimal-path-to-awesome) are being following in the sample - https://github.com/pnp/proxy-samples/tree/main/samples/demo-randomerror-js, I am getting an error.

Following is the error.

```
> demo-randomerror-js@1.0.0 start
> npx concurrently "npx http-server -p 3000 -s" "devproxy -c randomerror.devproxyrc.json"

[1] Unhandled exception. System.InvalidOperationException: Failed to convert configuration value at 'LogLevel' to type 'Microsoft.Extensions.Logging.LogLevel'.
[1]  ---> System.FormatException: info is not a valid value for LogLevel.
[1]  ---> System.ArgumentException: Requested value 'info' was not found.
[1]    at System.Enum.TryParseByName[TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TStorage& result)
[1]    at System.Enum.TryParseByValueOrName[TUnderlying,TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TUnderlying& result)
[1]    at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
[1]    at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
[1]    at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
[1]    --- End of inner exception stack trace ---
[1]    at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
[1]    at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, String path, Object& result, Exception& error)
[1]    --- End of inner exception stack trace ---
[1]    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
[1]    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
[1]    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperties(Object instance, IConfiguration configuration, BinderOptions options, ParameterInfo[] constructorParameters)
[1]    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
[1]    at Microsoft.DevProxy.CommandHandlers.ProxyCommandHandler.<>c.<.cctor>b__12_0()
[1]    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
[1]    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
[1]    at System.Lazy`1.CreateValue()
[1]    at Microsoft.DevProxy.CommandHandlers.ProxyCommandHandler.get_Configuration()
[1]    at Program.<>c__DisplayClass0_0.<<Main>$>b__9(ILoggingBuilder builder)
[1]    at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
[1]    at Microsoft.Extensions.Logging.LoggerFactory.Create(Action`1 configure)
[1]    at Program.<>c__DisplayClass0_0.<<Main>$>g__BuildLogger|0()
[1]    at Program.<Main>$(String[] args)
[1]    at Program.<Main>(String[] args)
```

It is already initiated in the Repo. https://github.com/pnp/proxy-samples/issues/5

### Expected behaviour

Run the application and start the Dev proxy

### Actual behaviour

Getting following error when you run `npm start`.

```> npx concurrently "npx http-server -p 3000 -s" "devproxy -c randomerror.devproxyrc.json"

[1] Unhandled exception. System.InvalidOperationException: Failed to convert configuration value at 'LogLevel' to type 'Microsoft.Extensions.Logging.LogLevel'.
[1]  ---> System.FormatException: info is not a valid value for LogLevel.
[1]  ---> System.ArgumentException: Requested value 'info' was not found.
[1]    at System.Enum.TryParseByName[TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TStorage& result)
[1]    at System.Enum.TryParseByValueOrName[TUnderlying,TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TUnderlying& result)
[1]    at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
[1]    at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
[1]    at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
[1]    --- End of inner exception stack trace ---
[1]    at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
[1]    at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, String path, Object& result, Exception& error)
[1]    --- End of inner exception stack trace ---
[1]    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
[1]    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
[1]    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperties(Object instance, IConfiguration configuration, BinderOptions options, ParameterInfo[] constructorParameters)
[1]    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
[1]    at Microsoft.DevProxy.CommandHandlers.ProxyCommandHandler.<>c.<.cctor>b__12_0()
[1]    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
[1]    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
[1]    at System.Lazy`1.CreateValue()
[1]    at Microsoft.DevProxy.CommandHandlers.ProxyCommandHandler.get_Configuration()
[1]    at Program.<>c__DisplayClass0_0.<<Main>$>b__9(ILoggingBuilder builder)
[1]    at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
[1]    at Microsoft.Extensions.Logging.LoggerFactory.Create(Action`1 configure)
[1]    at Program.<>c__DisplayClass0_0.<<Main>$>g__BuildLogger|0()
[1]    at Program.<Main>$(String[] args)
[1]    at Program.<Main>(String[] args)
```

### Steps to reproduce

- Follow the this [instructions](https://github.com/pnp/proxy-samples/tree/main/samples/demo-randomerror-js#minimal-path-to-awesome)
- run `npm start`

### Dev Proxy Version

0.23.0

### Operating system (environment)

macOS

### Shell

zsh

### Configuration file

Preset Config👇🏽

```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/dev-proxy/main/schemas/v0.14.1/rc.schema.json",
  "plugins": [
    {
      "name": "RetryAfterPlugin",
      "enabled": true,
      "pluginPath": "~appFolder/plugins/dev-proxy-plugins.dll"
    },
    {
      "name": "GenericRandomErrorPlugin",
      "enabled": true,
      "pluginPath": "~appFolder/plugins/dev-proxy-plugins.dll",
      "configSection": "genericRandomErrorPlugin"
    }
  ],
  "urlsToWatch": [
    "https://jsonplaceholder.typicode.com/*"
  ],
  "genericRandomErrorPlugin": {
    "errorsFile": "devproxy-errors.json"
  },
  "rate": 50,
  "labelMode": "text",
  "logLevel": "information"
}
```

Error Config  👇🏽
```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/dev-proxy/main/schemas/v0.14.1/genericrandomerrorplugin.schema.json",
  "responses": [
    {
      "statusCode": 400,
      "headers": [
        {
          "name": "Access-Control-Allow-Origin",
          "value": "*"
        }
      ],
      "body": {
        "message": "Bad Request",
        "details": "The server cannot process the request due to invalid syntax."
      }
    },
    {
      "statusCode": 401,
      "headers": [
        {
          "name": "Access-Control-Allow-Origin",
          "value": "*"
        }
      ],
      "body": {
        "message": "Unauthorized",
        "details": "The request requires user authentication."
      }
    },
    {
      "statusCode": 403,
      "headers": [
        {
          "name": "Access-Control-Allow-Origin",
          "value": "*"
        }
      ],
      "body": {
        "message": "Forbidden",
        "details": "The server understood the request, but refuses to authorize it."
      }
    },
    {
      "statusCode": 404,
      "headers": [
        {
          "name": "Access-Control-Allow-Origin",
          "value": "*"
        }
      ],
      "body": {
        "message": "Not Found",
        "details": "The requested resource could not be found."
      }
    },
    {
      "statusCode": 418,
      "headers": [
        {
          "name": "Access-Control-Allow-Origin",
          "value": "*"
        }
      ],
      "body": {
        "message": "I'm a teapot",
        "details": "The server refuses the attempt to brew coffee with a teapot."
      }
    },
    {
      "statusCode": 429,
      "headers": [
        {
          "name": "Retry-After",
          "value": "@dynamic"
        },
        {
          "name": "Access-Control-Allow-Origin",
          "value": "*"
        },
        {
          "name": "Access-Control-Allow-Headers",
          "value": "Retry-After"
        }
      ],
      "body": {
        "message": "Too Many Requests",
        "details": "The user has sent too many requests in a given amount of time (\"rate limiting\")."
      }
    },
    {
      "statusCode": 500,
      "headers": [
        {
          "name": "Access-Control-Allow-Origin",
          "value": "*"
        }
      ],
      "body": {
        "message": "Internal Server Error",
        "details": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
      }
    },
    {
      "statusCode": 503,
      "headers": [
        {
          "name": "Access-Control-Allow-Origin",
          "value": "*"
        }
      ],
      "body": {
        "message": "Service Unavailable",
        "details": "The server is currently unable to handle the request due to a temporary overload or maintenance. Please try again later."
      }
    }
  ]
}
```

**Comment by waldekmastykarz** [comment]
Thanks for letting us know! It's tracked and fixed here: https://github.com/pnp/proxy-samples/issues/5
